package main

import (
	"fmt"
	"github.com/leandroveronezi/go-terminal"
)

func main() {

	goTerminal.Clean()
	goTerminal.CursorLineColumn(1, 1)

	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundDefault)
	fmt.Println("Default")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundBlack)
	fmt.Println("Black")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundRed)
	fmt.Println("Red")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundGreen)
	fmt.Println("Green")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundYellow)
	fmt.Println("Yellow")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundBlue)
	fmt.Println("Blue")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundMagenta)
	fmt.Println("Magenta")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundCyan)
	fmt.Println("Cyan")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundLightGray)
	fmt.Println("LightGray")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundDarkGray)
	fmt.Println("DarkGray")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundLightRed)
	fmt.Println("LightRed")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundLightGreen)
	fmt.Println("LightGreen")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundLightYellow)
	fmt.Println("LightYellow")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundLightBlue)
	fmt.Println("LightBlue")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundLightMagenta)
	fmt.Println("LightMagenta")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundLightCyan)
	fmt.Println("LightCyan")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundWhite)
	fmt.Println("White")

	goTerminal.SetSGR(goTerminal.Reset, goTerminal.ForegroundDefault)

	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundDefault)
	fmt.Println("Default")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundBlack)
	fmt.Println("Black")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundRed)
	fmt.Println("Red")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundGreen)
	fmt.Println("Green")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundYellow)
	fmt.Println("Yellow")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundBlue)
	fmt.Println("Blue")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundMagenta)
	fmt.Println("Magenta")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundCyan)
	fmt.Println("Cyan")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundLightGray)
	fmt.Println("LightGray")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundDarkGray)
	fmt.Println("DarkGray")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundLightRed)
	fmt.Println("LightRed")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundLightGreen)
	fmt.Println("LightGreen")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundLightYellow)
	fmt.Println("LightYellow")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundLightBlue)
	fmt.Println("LightBlue")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundLightMagenta)
	fmt.Println("LightMagenta")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundLightCyan)
	fmt.Println("LightCyan")
	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundWhite)
	fmt.Println("White")

	goTerminal.SetSGR(goTerminal.Reset, goTerminal.BackgroundDefault)

}
