package main

import (
	"fmt"
	"github.com/leandroveronezi/go-terminal"
)

func main() {

	go_terminal.Clean()
	go_terminal.CursorLineColumn(1, 1)

	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundDefault)
	fmt.Println("Default")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundBlack)
	fmt.Println("Black")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundRed)
	fmt.Println("Red")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundGreen)
	fmt.Println("Green")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundYellow)
	fmt.Println("Yellow")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundBlue)
	fmt.Println("Blue")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundMagenta)
	fmt.Println("Magenta")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundCyan)
	fmt.Println("Cyan")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundLightGray)
	fmt.Println("LightGray")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundDarkGray)
	fmt.Println("DarkGray")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundLightRed)
	fmt.Println("LightRed")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundLightGreen)
	fmt.Println("LightGreen")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundLightYellow)
	fmt.Println("LightYellow")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundLightBlue)
	fmt.Println("LightBlue")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundLightMagenta)
	fmt.Println("LightMagenta")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundLightCyan)
	fmt.Println("LightCyan")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundWhite)
	fmt.Println("White")

	go_terminal.SetSGR(go_terminal.Reset, go_terminal.ForegroundDefault)

	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundDefault)
	fmt.Println("Default")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundBlack)
	fmt.Println("Black")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundRed)
	fmt.Println("Red")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundGreen)
	fmt.Println("Green")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundYellow)
	fmt.Println("Yellow")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundBlue)
	fmt.Println("Blue")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundMagenta)
	fmt.Println("Magenta")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundCyan)
	fmt.Println("Cyan")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundLightGray)
	fmt.Println("LightGray")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundDarkGray)
	fmt.Println("DarkGray")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundLightRed)
	fmt.Println("LightRed")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundLightGreen)
	fmt.Println("LightGreen")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundLightYellow)
	fmt.Println("LightYellow")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundLightBlue)
	fmt.Println("LightBlue")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundLightMagenta)
	fmt.Println("LightMagenta")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundLightCyan)
	fmt.Println("LightCyan")
	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundWhite)
	fmt.Println("White")

	go_terminal.SetSGR(go_terminal.Reset, go_terminal.BackgroundDefault)

}
